### ISSUE TITLE
Syntax error in aravel7-ghactions/.github/workflows/laravel_db_manual.yml file L76

### ISSUE THREAD

**Issue by HaiYassin** [roberto-butti/laravel7-ghactions#33]
@roberto-butti I m not sur but there is a syntax error in your Github action file on L76
`B_CONNECTION: mysql` L76 ; you would to write DB_CONNECTION no ?

**Comment by roberto-butti** [comment]
Good point @HaiYassin .
I'm going to fix it. Anyway there was no real issues because in the end in the configuration the default for DB_CONNECTION is mysql.
```
'default' => env('DB_CONNECTION', 'mysql'),
```

Thank you again for the feedback.
